name: Docker Build and Release

on:
  push:
    tags:
      - 'v*'  # 当推送版本标签时触发
  workflow_dispatch:  # 允许手动触发

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Create output directory
      run: mkdir -p out
      
    - name: Build Docker image
      run: docker build --tag onlyoffice-document-editors-builder .
      
    - name: Run Docker container to build products
      run: |
        docker run -v $PWD/out:/build_tools/out onlyoffice-document-editors-builder
        
    - name: Check build output
      run: |
        echo "Build output contents:"
        ls -la out/
        
    - name: Create release package
      run: |
        # 获取版本信息
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/}
        else
          VERSION=$(date +%Y%m%d-%H%M%S)
        fi
        
        # 创建压缩包
        cd out
        zip -r ../onlyoffice-build-${VERSION}.zip .
        cd ..
        
        echo "RELEASE_VERSION=${VERSION}" >> $GITHUB_ENV
        echo "RELEASE_FILE=onlyoffice-build-${VERSION}.zip" >> $GITHUB_ENV
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        body: |
          ## ONLYOFFICE Build Tools Release ${{ github.ref_name }}
          
          This release contains the compiled ONLYOFFICE products built using Docker.
          
          ### Contents
          - Document Server
          - Document Builder  
          - Desktop Editors
          
          ### Installation
          1. Download the `onlyoffice-build-${{ github.ref_name }}.zip` file
          2. Extract the contents
          3. Follow the setup instructions in the README.md
          
          Built from commit: ${{ github.sha }}
        draft: false
        prerelease: false
      id: create_release
        
    - name: Upload Release Asset
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./${{ env.RELEASE_FILE }}
        asset_name: ${{ env.RELEASE_FILE }}
        asset_content_type: application/zip
        
    - name: Upload build artifacts (for manual runs)
      if: github.event_name == 'workflow_dispatch'
      uses: actions/upload-artifact@v4
      with:
        name: onlyoffice-build-${{ env.RELEASE_VERSION }}
        path: out/
        retention-days: 30 